"use client";
import {useStore} from "@/components/Store";
export default function Automation(){
 const s=useStore();const x=s.settings;
 const bool=[["Bot WhatsApp","botEnabled",x.botEnabled,"Aktif 24 jam untuk admin/CS otomatis"],["AI Auto Reply","aiAutoReply",x.aiAutoReply,"AI boleh membalas otomatis"],["Human Takeover","humanTakeover",x.humanTakeover,"Owner bisa mengambil alih"],["Owner Approval","ownerApproval",x.ownerApproval,"Wajib sebelum fulfillment"]] as const;
 return <><div className="pageHead"><div><h1>Automation</h1><p>Kontrol bot, AI, follow-up, dan jam operasional.</p></div><span className="badge ok">Auto-saved</span></div>
 <div className="grid2"><div className="card">{bool.map(([label,key,val,desc])=><div className="settingRow" key={key}><div><b>{label}</b><span>{desc}</span></div><button className={"toggle "+(val?"on":"")} onClick={()=>s.setSettings({[key]:!val})}><div className="knob"/></button></div>)}</div>
 <div className="card"><h2 style={{fontSize:16,marginTop:0}}>Aturan respons</h2><div className="settingRow"><div><b>Mode operasional</b><span>Bot admin/CS aktif sepanjang hari.</span></div><span className="badge ok">24 Jam</span></div><label className="fieldLabel">Delay minimum <b>{x.delayMin}s</b></label><input className="input" type="range" min="1" max="30" value={x.delayMin} onChange={e=>s.setSettings({delayMin:Number(e.target.value)})}/><label className="fieldLabel">Delay maksimum <b>{x.delayMax}s</b></label><input className="input" type="range" min={x.delayMin} max="60" value={x.delayMax} onChange={e=>s.setSettings({delayMax:Number(e.target.value)})}/><div className="formGrid"><label className="fieldLabel">Jam mulai<input className="input" type="time" value={x.workingStart} onChange={e=>s.setSettings({workingStart:e.target.value})}/></label><label className="fieldLabel">Jam selesai<input className="input" type="time" value={x.workingEnd} onChange={e=>s.setSettings({workingEnd:e.target.value})}/></label><label className="fieldLabel span2">Maksimum follow-up<input className="input" type="number" min="0" max="10" value={x.maxFollowups} onChange={e=>s.setSettings({maxFollowups:Number(e.target.value)})}/></label></div></div></div>
 <div className="notice section"><b>Mode 24 jam aktif.</b> Jam operasional database diset 00:00–23:59. WAHA dan n8n tercatat terhubung lokal ke My Control.</div></>;
}